stages:
  - build
  - test
  - package
  - deploy
  
job1:
    stage: build
    script: 
        - dotnet build

job2:
    stage: test
    script:
        - cd tests
        - cd User.API.UnitTest
        - dotnet test

job3:
    stage: package
    script:
        - cd src
        - cd User.API
        - docker build -t userapi:test .
        - docker login -u testuser -p testpassword https://hub.docker.com/
        - docker tag userapi:test hub.docker.com/userapi:test
        - docker push hub.docker.com/userapi:test

job4:
    stage: deploy
    script:
        - docker run -d -p 80:80 --link mysql01:db --name userapi hub.docker.com/userapi:test